import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import test from 'node:test';
import { build } from 'esbuild';
import { isValidElement, type ReactElement, type ReactNode } from 'react';
import { createProject, createTask } from '../src/features/gantt/domain.ts';
import type { GanttProject, GanttTask } from '../src/features/gantt/types.ts';

type Element = ReactElement<Record<string, any>>;
function elements(node:ReactNode):Element[] {if(Array.isArray(node))return node.flatMap(elements);if(!isValidElement(node))return [];const el=node as Element;return [el,...elements(el.props.children)];}
function text(node:ReactNode):string {if(Array.isArray(node))return node.map(text).join('');if(isValidElement(node))return text((node as Element).props.children);return typeof node==='string'||typeof node==='number'?String(node):'';}
function find(tree:ReactNode,predicate:(element:Element)=>boolean):Element {const result=elements(tree).find(predicate);assert.ok(result,'expected event-bearing element');return result;}
const hasClass=(element:Element,value:string)=>element.props.className?.split(' ').includes(value);
const bundle=build({entryPoints:['src/features/gantt/GanttCanvas.tsx'],bundle:true,format:'cjs',platform:'node',target:'node22',write:false,external:['react','react/jsx-runtime','react-dom','lucide-react']});

// Real component/event handlers; DOM geometry/capture are doubles. Browser hit
// testing and actual pointer behavior require a separate UI verification.
async function harness(options:{editable?:boolean;completed?:boolean;statusFilter?:'all'|'active'|'completed';configure?:(project:GanttProject)=>void}={}) {
  const task=createTask('검증 작업','2026-09-05');task.endDate='2026-09-07';task.completed=options.completed??false;
  const project=createProject('검증 프로젝트',crypto.randomUUID(),'owner');project.tasks=[task];options.configure?.(project);
  const states:unknown[]=[],refs:any[]=[],effectSlots:Array<{deps?:unknown[];cleanup?:()=>void}>=[],callbackSlots:Array<{deps:unknown[];fn:unknown}>=[];
  let stateCursor=0,refCursor=0,effectCursor=0,callbackCursor=0;
  const pendingEffects:Array<()=>void>=[];
  const saved:Array<Partial<GanttTask>>=[],created:Array<{parentId:string|null;start:string;end:string}>=[],captured:number[]=[],released:number[]=[],selections:string[]=[],menus:string[]=[];
  const listeners=new Map<string,(event:any)=>void>(),windowListeners=new Map<string,(event:any)=>void>(),frames=new Map<number,()=>void>();let frameId=0,capturedPointer:number|null=null;
  function dom(classes='',parent:any=null,tag='DIV'):any {return {parentElement:parent,tagName:tag,dataset:{},classList:{contains:(value:string)=>classes.split(' ').includes(value)},
    closest(selector:string){for(const item of selector.split(',').map(value=>value.trim()))if(item.startsWith('.')?classes.split(' ').includes(item.slice(1)):item.toUpperCase()===tag)return this;return parent?.closest(selector)??null;},
    getBoundingClientRect:()=>({left:100,top:0,width:1200,bottom:40}),setPointerCapture(id:number){capturedPointer=id;captured.push(id);},hasPointerCapture:(id:number)=>capturedPointer===id,releasePointerCapture(id:number){capturedPointer=null;released.push(id);}};}
  const chart={...dom('gantt-canvas'),scrollLeft:0,scrollTop:0,clientWidth:1200,clientHeight:600,style:{setProperty(){}},addEventListener:(name:string,fn:(event:any)=>void)=>listeners.set(name,fn),removeEventListener:(name:string)=>listeners.delete(name),contains(target:any){for(let node=target;node;node=node.parentElement)if(node===chart)return true;return false;},focus(){}};
  const trackNode=dom('gantt-track',chart),barNode=dom('gantt-bar',trackNode,'BUTTON'),document={activeElement:chart};
  const window={addEventListener:(name:string,fn:(event:any)=>void)=>windowListeners.set(name,fn),removeEventListener:(name:string)=>windowListeners.delete(name)};
  const nodeRequire=createRequire(import.meta.url),react=nodeRequire('react');
  const module={exports:{} as {GanttCanvas:(props:any)=>ReactNode;localDate:()=>string;moveDate:(date:string,days:number)=>string}};
  const sameDeps=(a?:unknown[],b?:unknown[])=>!!a&&!!b&&a.length===b.length&&a.every((value,index)=>Object.is(value,b[index]));
  function effect(fn:()=>unknown,deps?:unknown[]){const slot=effectCursor++,previous=effectSlots[slot];if(!previous||!sameDeps(previous.deps,deps))pendingEffects.push(()=>{previous?.cleanup?.();const cleanup=fn();effectSlots[slot]={deps,cleanup:typeof cleanup==='function'?cleanup as ()=>void:undefined};});}
  new Function('require','module','exports','localStorage','requestAnimationFrame','cancelAnimationFrame','matchMedia','window','document',(await bundle).outputFiles[0].text)(
    (id:string)=>{if(id==='react')return {...react,useState(initial:unknown){const slot=stateCursor++;if(!(slot in states))states[slot]=typeof initial==='function'?(initial as ()=>unknown)():initial;return [states[slot],(next:unknown)=>{states[slot]=typeof next==='function'?(next as (x:unknown)=>unknown)(states[slot]):next;}];},useRef(initial:unknown){return refs[refCursor++]??={current:initial};},useMemo(fn:()=>unknown){return fn();},useCallback(fn:unknown,deps:unknown[]){const slot=callbackCursor++;if(!callbackSlots[slot]||!sameDeps(callbackSlots[slot].deps,deps))callbackSlots[slot]={fn,deps};return callbackSlots[slot].fn;},useEffect:effect,useLayoutEffect:effect};if(id==='react-dom')return {createPortal:(node:ReactNode)=>node};if(id==='lucide-react')return new Proxy({},{get:()=>()=>null});return nodeRequire(id);},
    module,module.exports,{getItem:()=>null,setItem(){}},(fn:()=>void)=>{frames.set(++frameId,fn);return frameId;},(id:number)=>frames.delete(id),()=>({matches:true}),window,document);
  const props={projects:[project],selected:[],statusFilter:options.statusFilter??'all',worker:'',collapsed:[],names:{},canEdit:()=>options.editable??true,onCollapse(){},onSelect(_projectId:string,taskId:string|null){selections.push(taskId??project.id);},onMenu(_project:GanttProject,selected:GanttTask|null){menus.push(selected?.id??project.id);},onPatch(_p:unknown,_t:unknown,patch:Partial<GanttTask>){saved.push(patch);},onAdd(_p:unknown,parentId:string|null,start:string,end:string){created.push({parentId,start,end});}};
  let tree:ReactNode,canvas:Element;
  function render(){stateCursor=refCursor=effectCursor=callbackCursor=0;tree=module.exports.GanttCanvas(props);canvas=find(tree,e=>e.props['aria-label']==='프로젝트 간트');(canvas as unknown as {ref:{current:unknown}}).ref.current=chart;pendingEffects.splice(0).forEach(fn=>fn());return tree;}
  render();
  const row=()=>find(tree,e=>hasClass(e,'gantt-row')&&text(e).includes(task.title)),bar=()=>find(row(),e=>hasClass(e,'gantt-bar')),track=()=>find(row(),e=>hasClass(e,'gantt-track'));
  function pointer(x:number,y=100,pointerId=7,target=chart):any {return {button:0,pointerId,clientX:x,clientY:y,currentTarget:chart,target,stopped:false,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;}};}
  function down(blank:boolean,x=400,y=100,edge?:string,pointerId=7){render();const node=blank?trackNode:barNode,target=edge?{...dom('gantt-resize',barNode,'SPAN'),dataset:{edge}}:node,event=pointer(x,y,pointerId,target);canvas.props.onPointerDownCapture?.(event);if(!event.stopped){event.currentTarget=node;(blank?track():bar()).props.onPointerDown?.(event);}return event;}
  return {saved,created,captured,released,selections,menus,chart,task,project,props,render,
    down(x=400,edge?:string,y=100,pointerId=7){return down(false,x,y,edge,pointerId);},blankDown(x:number,y=100,pointerId=7){return down(true,x,y,undefined,pointerId);},move(x:number,y=100,pointerId=7){canvas.props.onPointerMove(pointer(x,y,pointerId));},up(pointerId=7){canvas.props.onPointerUp(pointer(400,100,pointerId));},cancel(pointerId=7){canvas.props.onPointerCancel(pointer(400,100,pointerId));},lost(pointerId=7){canvas.props.onLostPointerCapture?.(pointer(400,100,pointerId));},
    click(detail=1){const event={...pointer(400),detail};canvas.props.onClickCapture?.(event);if(!event.stopped)row().props.onClick(event);return event;},doubleClick(x=340){const event=pointer(x,100,7,trackNode);event.currentTarget=trackNode;canvas.props.onDoubleClickCapture?.(event);if(!event.stopped)track().props.onDoubleClick(event);},
    mode(label:'화면 이동'|'작업 만들기'){find(render(),e=>e.type==='button'&&e.props['aria-label']===label).props.onClick();render();},
    key(key:string,down=true,input:boolean|'button'=false){const target=input?dom('',chart,input==='button'?'BUTTON':'INPUT'):chart,event={...pointer(0,0,7,target),key,code:key===' '?'Space':key,repeat:false};windowListeners.get(down?'keydown':'keyup')?.(event);render();return event;},blur(){windowListeners.get('blur')?.({});render();},
    menu(title:string){find(render(),e=>e.props['aria-label']===`${title} 메뉴`).props.onClick({...pointer(0),currentTarget:barNode});},rows(){return elements(render()).filter(e=>hasClass(e,'gantt-row')).map(e=>text(e));},rowCompleted(title:string){return text(find(render(),e=>hasClass(e,'gantt-row')&&text(e).includes(title))).includes('완료');},
    wheel(event:Record<string,unknown>){let prevented=false;listeners.get('wheel')!({clientX:600,deltaX:0,deltaY:-100,deltaMode:0,shiftKey:false,preventDefault(){prevented=true;},...event});return prevented;},frames(){for(const [id,fn]of [...frames]){frames.delete(id);fn();}},width:()=>states[0] as number,
    base:module.exports.moveDate(task.startDate<module.exports.localDate()?task.startDate:module.exports.localDate(),-6),moveDate:module.exports.moveDate,dispose(){effectSlots.forEach(slot=>slot.cleanup?.());},
  };
}

test('manual bar drag invokes date patch once on release and preserves duration',async()=>{const h=await harness();try{h.down();h.move(496);assert.deepEqual(h.saved,[]);h.up();assert.deepEqual(h.saved,[{startDate:'2026-09-07',endDate:'2026-09-09'}]);assert.deepEqual(h.captured,[7]);h.up();assert.equal(h.saved.length,1);}finally{h.dispose();}});
test('start and end resize patch only selected edge and reject inversion',async()=>{for(const [edge,x,expected]of [['start',448,{startDate:'2026-09-06'}],['end',544,{endDate:'2026-09-10'}]] as const){const h=await harness();try{h.down(400,edge);h.move(x);h.up();assert.deepEqual(h.saved,[expected]);}finally{h.dispose();}}const h=await harness();try{h.down(400,'start');h.move(592);h.up();assert.deepEqual(h.saved,[]);}finally{h.dispose();}});
test('default blank drag pans both axes without creating or editing an item',async()=>{const h=await harness();try{h.chart.scrollLeft=300;h.chart.scrollTop=200;h.blankDown(400,100);h.move(460,130);h.up();assert.equal(h.chart.scrollLeft,240);assert.equal(h.chart.scrollTop,170);assert.deepEqual(h.saved,[]);assert.deepEqual(h.created,[]);h.click();assert.deepEqual(h.selections,[]);}finally{h.dispose();}});
test('create mode makes ranges both ways while pan mode never double-click creates',async()=>{for(const [from,to,first,last]of [[340,484,5,8],[484,340,5,8]]){const h=await harness();try{h.doubleClick();assert.deepEqual(h.created,[]);h.mode('작업 만들기');h.blankDown(from);h.move(to);assert.deepEqual(h.created,[]);h.up();assert.deepEqual(h.created,[{parentId:null,start:h.moveDate(h.base,first),end:h.moveDate(h.base,last)}]);assert.deepEqual(h.saved,[]);}finally{h.dispose();}}});
test('Space temporarily pans over bars and release restores date editing',async()=>{const h=await harness();try{h.chart.scrollLeft=300;assert.equal(h.key(' ').defaultPrevented,true);h.down();h.move(448,140);h.up();assert.equal(h.chart.scrollLeft,252);assert.deepEqual(h.saved,[]);h.key(' ',false);h.down();h.move(448);h.up();assert.deepEqual(h.saved,[{startDate:'2026-09-06',endDate:'2026-09-08'}]);}finally{h.dispose();}});
test('Space in text input neither arms pan nor prevents typing',async()=>{const h=await harness();try{assert.equal(h.key(' ',true,true).defaultPrevented,false);h.down();h.move(448);h.up();assert.equal(h.saved.length,1);}finally{h.dispose();}});
test('Space leaves menu and collapse button keyboard activation available',async()=>{const h=await harness();try{assert.equal(h.key(' ',true,'button').defaultPrevented,false);h.down();h.move(448);h.up();assert.equal(h.saved.length,1);}finally{h.dispose();}});
test('foreign pointer move release and lost capture cannot finish active gesture',async()=>{const h=await harness();try{h.down();h.move(544,100,8);h.up(8);h.lost(8);assert.deepEqual(h.saved,[]);h.move(448);h.up();assert.deepEqual(h.saved,[{startDate:'2026-09-06',endDate:'2026-09-08'}]);}finally{h.dispose();}});
test('cancel lost capture Escape and blur discard drafts and release captures',async()=>{for(const abort of ['cancel','lost','escape','blur'] as const){const h=await harness();try{h.down();h.move(496);if(abort==='escape')h.key('Escape');else h[abort]();h.up();assert.deepEqual(h.saved,[]);if(abort!=='lost')assert.deepEqual(h.released,[7]);h.down();h.move(448);h.up();assert.equal(h.saved.length,1);}finally{h.dispose();}}});
test('blur clears Space and a later click is not eaten after cancellation',async()=>{const h=await harness();try{h.key(' ');h.down();h.move(450);h.blur();h.up();h.down();h.up();h.click();assert.equal(h.selections.length,1);h.down();h.move(448);h.up();assert.equal(h.saved.length,1);}finally{h.dispose();}});
test('tiny motion remains a click and real pan suppresses click and double-click',async()=>{const h=await harness();try{h.blankDown(400);h.move(402,101);h.up();h.click();assert.equal(h.selections.length,1);h.mode('작업 만들기');h.key(' ');h.blankDown(400);h.move(480);h.up();h.key(' ',false);h.click();h.doubleClick();assert.equal(h.selections.length,1);assert.deepEqual(h.created,[]);}finally{h.dispose();}});
test('completed and read-only charts retain navigation but never mutate dates',async()=>{for(const options of [{editable:false},{completed:true},{configure:(p:GanttProject)=>{p.completed=true;}}]){const h=await harness(options);try{h.chart.scrollLeft=300;h.blankDown(400);h.move(448);h.up();assert.equal(h.chart.scrollLeft,252);h.down();h.move(496);h.up();h.mode('작업 만들기');h.blankDown(340);h.move(484);h.up();assert.deepEqual(h.saved,[]);assert.deepEqual(h.created,[]);}finally{h.dispose();}}});
test('all view keeps completed work visible with completion badge and row menu',async()=>{const h=await harness({completed:true});try{assert.ok(h.rows().some(row=>row.includes('검증 작업')));assert.equal(h.rowCompleted('검증 작업'),true);h.menu('검증 작업');assert.deepEqual(h.menus,[h.task.id]);assert.deepEqual(h.created,[]);assert.deepEqual(h.saved,[]);}finally{h.dispose();}});
test('active and completed filters keep mixed ancestors and empty completed groups',async()=>{const configure=(p:GanttProject)=>{const group=createTask('혼합 그룹');group.kind='group';const empty=createTask('빈 완료 그룹');empty.kind='group';empty.completed=true;const finished=createTask('끝난 작업');finished.completed=true;finished.parentId=group.id;p.tasks[0].parentId=group.id;p.tasks=[group,...p.tasks,finished,empty];};const h=await harness({configure});try{assert.equal(h.rows().length,5);assert.equal(h.rowCompleted('혼합 그룹'),false);assert.equal(h.rowCompleted('빈 완료 그룹'),true);h.props.statusFilter='active';const active=h.rows();assert.equal(active.length,3);assert.ok(active.some(row=>row.includes('혼합 그룹')));assert.ok(active.some(row=>row.includes('검증 작업')));assert.ok(!active.some(row=>row.includes('끝난 작업')));h.props.statusFilter='completed';const completed=h.rows();assert.equal(completed.length,4);assert.ok(completed.some(row=>row.includes('혼합 그룹')));assert.ok(completed.some(row=>row.includes('끝난 작업')));assert.ok(completed.some(row=>row.includes('빈 완료 그룹')));assert.ok(!completed.some(row=>row.includes('검증 작업')));}finally{h.dispose();}});
test('completed nested empty group keeps every ancestor in completed filter',async()=>{const h=await harness({statusFilter:'completed',configure(p){const parent=createTask('상위 그룹');parent.kind='group';const empty=createTask('하위 빈 그룹');empty.kind='group';empty.completed=true;empty.parentId=parent.id;p.tasks=[parent,empty];}});try{const rows=h.rows();assert.equal(rows.length,3);assert.ok(rows.some(row=>row.includes('상위 그룹')));assert.ok(rows.some(row=>row.includes('하위 빈 그룹')));}finally{h.dispose();}});
test('wheel keeps cursor anchor and Shift scrolls without zoom',async()=>{const h=await harness();try{h.chart.scrollLeft=320;const cursor=500,before=(h.chart.scrollLeft+cursor)/h.width();assert.equal(h.wheel({}),true);h.frames();assert.ok(h.width()>48);assert.ok(Math.abs((h.chart.scrollLeft+cursor)/h.width()-before)<1e-9);const width=h.width(),scroll=h.chart.scrollLeft;h.wheel({shiftKey:true,deltaY:40});h.frames();assert.equal(h.width(),width);assert.equal(h.chart.scrollLeft,scroll+40);h.down();const held=h.chart.scrollLeft;assert.equal(h.wheel({}),false);h.frames();assert.equal(h.chart.scrollLeft,held);h.cancel();}finally{h.dispose();}});
