import assert from 'node:assert/strict';
import test from 'node:test';
import { applyCommand, canViewSpace, canEditProject, canManageSpace, createSpace, createProject } from '../src/features/gantt/domain.ts';
import { createGanttStore } from '../src/features/gantt/useGanttStore.ts';
import type { GanttSnapshot } from '../src/features/gantt/types.ts';
function fixture(){const space=createSpace('원본','owner');const project=createProject('원본',space.id,'owner');const calendarLink={calendarId:crypto.randomUUID(),linkId:crypto.randomUUID(),actorId:'viewer',visibility:'team' as const,canEdit:false,canUnlink:true,isAdminOverview:false};return {spaces:[{...space,calendarLink}],projects:[{...project,calendarLink}]} satisfies GanttSnapshot;}
test('linked team access is actor scoped and does not grant Gantt write or ownership',()=>{const snapshot=fixture();assert.equal(canViewSpace(snapshot.spaces[0],'viewer'),true);assert.equal(canViewSpace(snapshot.spaces[0],'stranger'),false);assert.equal(canManageSpace(snapshot.spaces[0],'owner'),false);assert.equal(canEditProject(snapshot,'owner',snapshot.projects[0]),false);});
test('normal save cannot forge or strip linked authority',()=>{const snapshot=fixture();const project={...snapshot.projects[0],ownerId:'viewer'};assert.throws(()=>applyCommand(snapshot,'viewer',{type:'saveProject',project,expectedRevision:1}));const forged={...createSpace('forged','viewer'),calendarLink:snapshot.spaces[0].calendarLink};assert.throws(()=>applyCommand({spaces:[],projects:[]},'viewer',{type:'saveSpace',space:forged,expectedRevision:null}));});
test('unlink is optimistic, rejects stale binding, and keeps source out of commands',()=>{const snapshot=fixture();const link=snapshot.spaces[0].calendarLink;assert.deepEqual(applyCommand(snapshot,'viewer',{type:'unlinkCalendar',calendarId:link.calendarId,linkId:link.linkId}),{spaces:[],projects:[]});assert.throws(()=>applyCommand(snapshot,'viewer',{type:'unlinkCalendar',calendarId:link.calendarId,linkId:crypto.randomUUID()}));});
test('link/unlink store uses canonical result and rolls back failures without undo entries',async()=>{const canonical=fixture();const link=canonical.spaces[0].calendarLink;let saved=false;const store=createGanttStore();await store.getState().initialize('viewer',{read:async()=>saved?canonical:{spaces:[],projects:[]},execute:async(request)=>{if(request.command.type==='linkCalendar'){saved=true;return canonical;}throw new Error('denied');}});await store.getState().execute({type:'linkCalendar',calendarId:link.calendarId});assert.deepEqual(store.getState().snapshot,canonical);assert.equal(store.getState().canUndo,false);await assert.rejects(store.getState().execute({type:'unlinkCalendar',calendarId:link.calendarId,linkId:link.linkId}),/denied/);assert.deepEqual(store.getState().snapshot,canonical);await store.getState().initialize(null);});

test('link response loss confirms the same visible calendar without a duplicate error',async()=>{const canonical=fixture();const link=canonical.spaces[0].calendarLink;let committed=false;const store=createGanttStore();await store.getState().initialize('viewer',{read:async()=>committed?canonical:{spaces:[],projects:[]},execute:async()=>{committed=true;throw new Error('response lost');}});await store.getState().execute({type:'linkCalendar',calendarId:link.calendarId});assert.deepEqual(store.getState().snapshot,canonical);assert.equal(store.getState().error,null);await store.getState().initialize(null);});
