const path=require('node:path');
const assert=require('node:assert/strict');
const {createRequire}=require('node:module');
const req=createRequire(path.join(process.cwd(),'package.json'));
const {build}=req('esbuild'), React=req('react');
function els(node){if(Array.isArray(node))return node.flatMap(els);if(!React.isValidElement(node))return [];return [node,...els(node.props.children)];}
function txt(node){if(Array.isArray(node))return node.map(txt).join('');if(React.isValidElement(node))return txt(node.props.children);return typeof node==='string'||typeof node==='number'?String(node):'';}
const {test}=require('node:test');
function check(name,fn){test(name,fn);}
async function bundle(file,external=[]){return (await build({entryPoints:[file],bundle:true,format:'cjs',platform:'node',write:false,loader:{'.css':'empty'},external:['react','react/jsx-runtime','react-dom','lucide-react',...external]})).outputFiles[0].text;}
function icons(){return new Proxy({},{get:()=>()=>null});}
(async()=>{
 const model={exports:{}};new Function('module','exports',await bundle('src/features/gantt/treeModel.ts'))(model,model.exports);
 const task=(id,title,parentId=null)=>({id,title,parentId,kind:'task',sortOrder:0,completed:false,progress:0,workers:[],startDate:'2026-09-01',endDate:'2026-09-02',allDay:true,startTime:'',endTime:''});
 const a=task('b-id','원래 첫 작업'), b=task('a-id','원래 둘째 작업');const project={id:'p',spaceId:'s',name:'프로젝트',ownerId:'owner',completed:false,tasks:[a,b]};
 check('Tree order matches Canvas stable order when existing sortOrder values tie',()=>assert.deepEqual(model.exports.orderedChildren(project,null).map(t=>t.id),['b-id','a-id']));
 const treeMod={exports:{}};new Function('require','module','exports',await bundle('src/features/gantt/GanttTree.tsx',['./GanttShareTooltip']))(id=>id==='lucide-react'?icons():id==='./GanttShareTooltip'?{GanttShareTooltip:()=>null}:req(id),treeMod,treeMod.exports);
 const group={...task('g','그룹'),kind:'group'}, completed={...task('c','완료 작업','g'),completed:true,progress:100};const incomplete=task('i','미완료 작업');const selected=[],toggles=[];
 const props={spaces:[{id:'s',name:'내 폴더',ownerId:'owner',shared:false}],projects:[{...project,tasks:[group,completed,incomplete]}],userId:'owner',users:[],selectedProject:'p',selected:['c'],closedSpaces:[],collapsed:[],hidden:[],filter:'completed',search:'',worker:'',onToggleFolder(){},onToggleBranch(id){toggles.push(id);},onToggleVisibility(){},onSelect(p,t){selected.push([p,t]);},onFolderSettings(){},onMenu(){}};
 check('Completed tree preserves ancestry and real selection/collapse handlers',()=>{let tree=treeMod.exports.GanttTree(props);const rows=els(tree).filter(e=>e.props.role==='treeitem');assert.equal(rows.length,4);assert.ok(rows.some(e=>e.props['aria-label']==='완료 작업 · 작업 · 내 폴더 › 프로젝트 › 그룹'));assert.ok(!rows.some(e=>String(e.props['aria-label']).includes('미완료 작업')));els(tree).find(e=>e.type==='button'&&e.props.className==='gantt-tree-title'&&txt(e)==='완료 작업').props.onClick();assert.deepEqual(selected,[['p','c']]);els(tree).find(e=>e.props['aria-label']==='그룹 접기').props.onClick();assert.deepEqual(toggles,['g']);props.collapsed=['g'];tree=treeMod.exports.GanttTree(props);assert.ok(!els(tree).some(e=>e.props.role==='treeitem'&&String(e.props['aria-label']).startsWith('완료 작업')));});
 const states=[],refs=[];let state=0,ref=0,effects=[],frames=[],root,portalTarget,focusRestored=0,reduceMotion=false;const changes=[],dialog={kind:'dialog'},body={kind:'body'};
 const window={innerHeight:600,innerWidth:900,addEventListener(){},removeEventListener(){}},document={body,addEventListener(){},removeEventListener(){}};
 const glass={exports:{}};new Function('require','module','exports','window','document','requestAnimationFrame','cancelAnimationFrame',await bundle('src/components/common/GlassDropdown.tsx',['framer-motion','@/utils/cn','@/components/common/CompactIconLabel']))(id=>id==='react'?{...React,useState(initial){const slot=state++;if(!(slot in states))states[slot]=typeof initial==='function'?initial():initial;return [states[slot],next=>{states[slot]=typeof next==='function'?next(states[slot]):next;}];},useRef(initial){return refs[ref++]??=( {current:initial} );},useCallback(fn){return fn;},useId(){return 'menu';},useEffect(fn){effects.push(fn);}}:id==='react-dom'?{createPortal(node,target){portalTarget=target;return node;}}:id==='framer-motion'?{useReducedMotion:()=>reduceMotion,AnimatePresence:({children})=>children,motion:{div:'motion.div'}}:id==='lucide-react'?icons():id==='@/utils/cn'?{cn:(...v)=>v.filter(Boolean).join(' ')}:id==='@/components/common/CompactIconLabel'?{CompactIconLabel:()=>null}:req(id),glass,glass.exports,window,document,fn=>{frames.push(fn);return 1;},()=>{});
 const glassProps={options:[{value:'x',label:'금지',disabled:true},{value:'a',label:'허용 A'},{value:'b',label:'허용 B'},...Array.from({length:9},(_,i)=>({value:'more'+i,label:'추가 선택 '+i}))],value:'a',onChange:v=>changes.push(v),label:'선택',portal:true};
 function render(){state=ref=0;root=glass.exports.GlassDropdown(glassProps);refs[0].current={contains:()=>false};refs[1].current={getBoundingClientRect:()=>({top:260,bottom:292,left:100,width:180}),closest:()=>dialog,focus(){focusRestored++;}};refs[2].current={getBoundingClientRect:()=>({height:320}),querySelector:()=>({scrollIntoView(){}}),contains:()=>false};for(const fn of effects.splice(0))fn();for(const fn of frames.splice(0))fn();return root;}
 const press=key=>{root.props.onKeyDown({key,preventDefault(){},stopPropagation(){}});render();};render();
 check('Dropdown keyboard skips disabled option, direct disabled handler rejects selection, dialog portal remains inside dialog',()=>{press('ArrowDown');press('Enter');assert.deepEqual(changes,['a']);els(root).find(e=>e.props.role==='combobox').props.onClick();render();const forbidden=els(root).find(e=>e.props.role==='option'&&e.props.disabled);forbidden.props.onClick();assert.deepEqual(changes,['a']);assert.equal(portalTarget,dialog);});
 check('Portal menu bottom stays inside a 600px viewport at the middle trigger',()=>{render();const menu=els(root).find(e=>e.type==='motion.div');const list=els(root).find(e=>e.props.role==='listbox');const bottom=menu.props.style.top+Math.min(320,list.props.style.maxHeight);assert.ok(bottom<=592,`menu top=${menu.props.style.top}, measured height=320, bottom=${bottom}, safe bottom=592`);});

 check('Dropdown pointer selection restores its trigger focus',()=>{const before=focusRestored;els(root).find(e=>e.props.role==='option'&&e.props['aria-selected']===false&&!e.props.disabled).props.onClick();render();assert.equal(focusRestored,before+1);assert.equal(els(root).find(e=>e.props.role==='combobox').props['aria-expanded'],false);});
 check('Dropdown respects reduced motion without changing portal placement',()=>{reduceMotion=true;els(root).find(e=>e.props.role==='combobox').props.onClick();render();const menu=els(root).find(e=>e.type==='motion.div');assert.equal(menu.props.initial,false);assert.equal(menu.props.transition.duration,0);assert.equal(portalTarget,dialog);press('Escape');});
})().catch(e=>{console.error(e);process.exitCode=2;});
