import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';
import { EVENT_COLORS, type BflowCalendar } from '@/types/calendar';
import type { GanttProject, GanttSpace, GanttTask } from './types';
import { floatingGlassStyle } from '@/utils/glassStyles';

export function GanttModal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{if(previous?.isConnected)previous.focus();};},[]);
  return createPortal(<dialog ref={ref} className="gantt-modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><header><h2>{title}</h2><button aria-label="닫기" onClick={onClose}><X size={18}/></button></header>{children}</dialog>,document.body);
}
export function GanttSpaceDialog({space,actorId,users,calendars,onSave,onClose,onDelete,projectCount=0}:{space:GanttSpace|null;actorId:string;users:Array<{id:string;name:string}>;calendars:BflowCalendar[];onSave:(space:GanttSpace)=>Promise<void>;onClose:()=>void;onDelete?:()=>Promise<void>;projectCount?:number}) {
  const [draft,setDraft]=useState<GanttSpace>(space||{id:crypto.randomUUID(),ownerId:actorId,name:'',shared:false,members:[],revision:1});
  const [error,setError]=useState(''),[pending,setPending]=useState(false),[deleting,setDeleting]=useState(false);
  const removesMembers=space?.shared&&space.members.some(member=>member.userId!==space.ownerId&&(!draft.shared||!draft.members.some(current=>current.userId===member.userId)));
  return <GanttModal title={space?'폴더 설정':'새 폴더'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setPending(true);try{await onSave({...draft,name:draft.name.trim()});onClose();}catch(e){setError(String((e as Error).message));}finally{setPending(false);}}}>
    <p>프로젝트를 담는 폴더입니다. 공유하면 폴더 안의 프로젝트도 함께 볼 수 있습니다.</p><label className="gantt-field">폴더 이름<input autoFocus required maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
    <label className="gantt-check"><input type="checkbox" checked={draft.shared} onChange={e=>setDraft({...draft,shared:e.target.checked})}/>팀원과 공유</label>
    {draft.shared&&<><label className="gantt-field">캘린더에서 멤버 가져오기<select defaultValue="" onChange={e=>{const c=calendars.find(c=>c.id===e.target.value);if(c)setDraft({...draft,members:[...new Set([c.ownerId,...c.members.map(m=>m.userId)])].filter(id=>id!==actorId).map(userId=>({userId,canEdit:c.ownerId===userId||!!c.members.find(m=>m.userId===userId)?.canEdit}))});}}><option value="">직접 선택</option>{calendars.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>가져온 뒤에는 캘린더와 별도로 공유 대상을 관리합니다.</small></label><div className="gantt-members">{users.filter(u=>u.id!==actorId).map(u=>{const member=draft.members.find(m=>m.userId===u.id);return <div key={u.id}><label><input type="checkbox" checked={!!member} onChange={e=>setDraft({...draft,members:e.target.checked?[...draft.members,{userId:u.id,canEdit:false}]:draft.members.filter(m=>m.userId!==u.id)})}/>{u.name}</label>{member&&<select aria-label={`${u.name} 권한`} value={member.canEdit?'edit':'view'} onChange={e=>setDraft({...draft,members:draft.members.map(m=>m.userId===u.id?{...m,canEdit:e.target.value==='edit'}:m)})}><option value="view">보기</option><option value="edit">편집</option></select>}</div>;})}</div></>}
    {removesMembers&&<p>제외한 멤버의 프로젝트는 폴더 소유자가 이어서 관리합니다. 프로젝트 소유자나 공유 대상이 정리되면 실행 취소 기록이 초기화됩니다.</p>}
    {error&&<p className="gantt-error" role="alert">{error}</p>}<div className="gantt-dialog-actions"><button type="button" onClick={onClose}>취소</button><button className="primary" disabled={pending||!draft.name.trim()}>저장</button></div>
    {space&&onDelete&&space.ownerId===actorId&&<div className="gantt-folder-delete"><hr/><p>{projectCount?`프로젝트 ${projectCount}개가 있습니다. 안의 프로젝트를 각각 삭제한 뒤 폴더를 삭제할 수 있습니다.`:'빈 폴더입니다. 삭제해도 실행 취소로 되돌릴 수 있습니다.'}</p>{deleting?<><p>‘{space.name}’ 폴더를 삭제할까요?</p><button type="button" disabled={pending} onClick={()=>setDeleting(false)}>삭제 취소</button><button type="button" className="danger" disabled={pending||projectCount>0} onClick={async()=>{setPending(true);setError('');try{await onDelete();onClose();}catch(e){setError((e as Error).message);}finally{setPending(false);}}}>삭제 확인</button></>:<button type="button" className="danger" disabled={pending||projectCount>0} onClick={()=>setDeleting(true)}>폴더 삭제</button>}</div>}
  </form></GanttModal>;
}
export interface GanttContextTarget { project:GanttProject; task:GanttTask|null; x:number; y:number }
type GanttQuickEditPatch = Partial<Omit<GanttTask,'color'>&Omit<GanttProject,'color'>>&{color?:string|null};
export function GanttContextMenu({target,canEdit,onClose,onDetail,onSave,onComplete,onDelete,completed}:{target:GanttContextTarget;canEdit:boolean;onClose:()=>void;onDetail:()=>void;onSave:(patch:GanttQuickEditPatch)=>Promise<void>;onComplete:()=>void;onDelete?:()=>void;completed?:boolean}) {
  const ref=useRef<HTMLDivElement>(null),firstFocus=useRef<HTMLElement|null>(null);
  const [position,setPosition]=useState({left:target.x,top:target.y}),[editing,setEditing]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(false);
  const t=target.task,p=target.project,[title,setTitle]=useState(t?.title||p.name),[memo,setMemo]=useState(t?t.memo:p.memo),[start,setStart]=useState(t?.startDate||''),[end,setEnd]=useState(t?.endDate||'');
  const [color,setColor]=useState<string|null>(t?t.color:p.color);
  useLayoutEffect(()=>{const r=ref.current?.getBoundingClientRect();if(r)setPosition({left:Math.max(8,Math.min(target.x,innerWidth-r.width-8)),top:Math.max(8,Math.min(target.y,innerHeight-r.height-8))});},[target,editing]);
  useEffect(()=>{firstFocus.current=document.activeElement as HTMLElement;ref.current?.querySelector<HTMLElement>('button')?.focus();const outside=(e:Event)=>{if(!ref.current?.contains(e.target as Node))onClose();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(!editing&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const list=[...ref.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];const index=list.indexOf(document.activeElement as HTMLButtonElement);list[(index+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus();}};document.addEventListener('pointerdown',outside,true);document.addEventListener('keydown',key);document.addEventListener('scroll',outside,true);return()=>{document.removeEventListener('pointerdown',outside,true);document.removeEventListener('keydown',key);document.removeEventListener('scroll',outside,true);firstFocus.current?.isConnected&&firstFocus.current.focus();};},[onClose,editing]);
  const save=async(patch:GanttQuickEditPatch)=>{setPending(true);try{await onSave(patch);onClose();}catch(e){setError((e as Error).message);}finally{setPending(false);}};
  const chooseColor=(next:string|null)=>{if(editing){setColor(next);setError('');}else void save({color:next});};
  return createPortal(<div ref={ref} role={editing?'dialog':'menu'} aria-label={editing?'빠른 편집':'간트 빠른 작업'} className="gantt-context" style={{...floatingGlassStyle,...position}}>
    <strong>{t?.title||p.name}</strong>{editing?<form onSubmit={e=>{e.preventDefault();void save({...t?{title,...t.kind!=='group'?{startDate:start,endDate:t.kind==='milestone'?start:end}:{}}:{name:title},memo,color});}}><label className="gantt-field">제목<input autoFocus required value={title} onChange={e=>setTitle(e.target.value)}/></label>{t&&t.kind!=='group'&&<div className="gantt-pair"><label className="gantt-field">시작일<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="gantt-field">종료일<input type="date" min={start} required value={t.kind==='milestone'?start:end} onChange={e=>setEnd(e.target.value)} disabled={t.kind==='milestone'}/></label></div>}<label className="gantt-field">메모<textarea value={memo} onChange={e=>setMemo(e.target.value)}/></label><button className="primary" disabled={!canEdit||pending}>저장</button></form>:<><button role="menuitem" disabled={!canEdit} onClick={()=>setEditing(true)}>빠른 편집</button><button role="menuitem" onClick={onDetail}>상세 열기</button><button role="menuitem" disabled={!canEdit} onClick={onComplete}>{(completed??(t?t.completed||t.progress===100:p.completed))?'다시 열기':'완료 표시'}</button><div className="gantt-context-divider"/>{onDelete&&<button className="danger" role="menuitem" disabled={!canEdit||pending} onClick={onDelete}>{t?.kind==='group'?'그룹 삭제':t?'작업 삭제':'프로젝트 삭제'}</button>}<div className="gantt-context-divider"/><small>막대 색상</small></>}
    <div className="gantt-swatches">{EVENT_COLORS.map(value=><button key={value} type="button" role={editing?undefined:'menuitemradio'} aria-checked={editing?undefined:(t?t.color:p.color)?.toLowerCase()===value.toLowerCase()} aria-pressed={editing?color?.toLowerCase()===value.toLowerCase():undefined} aria-label={`색상 ${value}`} disabled={!canEdit||pending} style={{background:value}} onClick={()=>chooseColor(value)}/>)}</div>{t&&<button disabled={!canEdit||pending} aria-pressed={editing?color===null:undefined} onClick={()=>chooseColor(null)}>상위 색상 따르기</button>}{!canEdit&&<small>보기 권한으로 열었습니다.</small>}{error&&<p role="alert" className="gantt-error">{error}</p>}
  </div>,document.body);
}
