-- Generated by Supabase CLI migration new calendar_external_feed (2.81.3).
-- Apply after app sessions, shared calendars/tags, and Gantt projection migrations.
-- Existing calendars remain unpublished: only an explicit owner command creates a feed.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='45s';
CREATE TABLE IF NOT EXISTS public.calendar_external_feeds (
  calendar_id UUID PRIMARY KEY REFERENCES public.calendars(id) ON DELETE CASCADE,
  owner_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT UNIQUE CHECK(token_hash IS NULL OR token_hash ~ '^[0-9a-f]{64}$'),
  enabled BOOLEAN NOT NULL DEFAULT false,
  revision UUID NOT NULL DEFAULT gen_random_uuid(),
  issued_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((enabled AND token_hash IS NOT NULL AND issued_at IS NOT NULL) OR (NOT enabled AND token_hash IS NULL))
);
ALTER TABLE public.calendar_external_feeds ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.calendar_external_feeds FROM PUBLIC,anon,authenticated,service_role;
COMMENT ON TABLE public.calendar_external_feeds IS 'Owner-opted-in read-only calendar feeds; stores SHA256 only, never raw subscription bearer tokens.';

CREATE OR REPLACE FUNCTION public.calendar_session_feed_status(p_session_token TEXT,p_calendar_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE actor TEXT:=public.app_session_user_id(p_session_token); feed public.calendar_external_feeds%ROWTYPE;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.calendars WHERE id=p_calendar_id AND owner_id=actor) THEN
    RAISE EXCEPTION '캘린더 소유자만 외부 구독을 관리할 수 있습니다' USING ERRCODE='42501';
  END IF;
  SELECT * INTO feed FROM public.calendar_external_feeds WHERE calendar_id=p_calendar_id AND owner_id=actor;
  RETURN jsonb_build_object('calendarId',p_calendar_id,'enabled',coalesce(feed.enabled,false),
    'issuedAt',CASE WHEN feed.enabled THEN feed.issued_at ELSE NULL END,'revision',feed.revision);
END $$;

-- The main process creates 32 cryptographically random bytes and submits only
-- SHA256(raw token). The raw URL is delivered to the owner once by main, not stored here.
CREATE OR REPLACE FUNCTION public.calendar_session_feed_manage(
 p_session_token TEXT,p_calendar_id UUID,p_action TEXT,p_token_hash TEXT DEFAULT NULL,p_expected_revision UUID DEFAULT NULL)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE actor TEXT:=public.app_session_user_id(p_session_token); feed public.calendar_external_feeds%ROWTYPE;
BEGIN
  -- Lock the canonical owner before the feed to serialize ownership transfer and
  -- feed lifecycle commands. Source event data/membership are never modified.
  PERFORM 1 FROM public.calendars WHERE id=p_calendar_id AND owner_id=actor FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION '캘린더 소유자만 외부 구독을 관리할 수 있습니다' USING ERRCODE='42501'; END IF;
  IF p_action IS NULL OR p_action NOT IN ('enable','rotate','revoke') THEN
    RAISE EXCEPTION '외부 구독 요청이 올바르지 않습니다' USING ERRCODE='22023';
  END IF;
  IF (p_action IN ('enable','rotate') AND (p_token_hash IS NULL OR p_token_hash !~ '^[0-9a-f]{64}$'))
     OR (p_action='revoke' AND p_token_hash IS NOT NULL) THEN
    RAISE EXCEPTION '외부 구독 토큰 해시가 올바르지 않습니다' USING ERRCODE='22023';
  END IF;
  SELECT * INTO feed FROM public.calendar_external_feeds WHERE calendar_id=p_calendar_id FOR UPDATE;
  -- Safe retries of the exact issuance never rotate another token. Repeated revoke
  -- of an already-disabled feed is also harmless; no stale command changes state.
  IF (p_action IN ('enable','rotate') AND feed.enabled AND feed.token_hash=p_token_hash)
     OR (p_action='revoke' AND NOT coalesce(feed.enabled,false)) THEN
    RETURN public.calendar_session_feed_status(p_session_token,p_calendar_id);
  END IF;
  IF p_expected_revision IS DISTINCT FROM feed.revision THEN
    RAISE EXCEPTION '외부 구독 설정이 변경되었습니다. 새로고침한 뒤 다시 시도해 주세요' USING ERRCODE='40001';
  END IF;
  IF p_action='enable' AND coalesce(feed.enabled,false) THEN
    RAISE EXCEPTION '이미 활성화된 외부 구독은 링크 재발급을 사용해 주세요' USING ERRCODE='55000';
  ELSIF p_action='rotate' AND NOT coalesce(feed.enabled,false) THEN
    RAISE EXCEPTION '외부 구독을 먼저 활성화해 주세요' USING ERRCODE='55000';
  END IF;
  INSERT INTO public.calendar_external_feeds(calendar_id,owner_id,token_hash,enabled,revision,issued_at,updated_at)
  VALUES(p_calendar_id,actor,p_token_hash,p_action<>'revoke',gen_random_uuid(),CASE WHEN p_action='revoke' THEN NULL ELSE now() END,now())
  ON CONFLICT(calendar_id) DO UPDATE SET owner_id=EXCLUDED.owner_id,token_hash=EXCLUDED.token_hash,enabled=EXCLUDED.enabled,
    revision=EXCLUDED.revision,issued_at=EXCLUDED.issued_at,updated_at=EXCLUDED.updated_at;
  RETURN public.calendar_session_feed_status(p_session_token,p_calendar_id);
END $$;

-- Ownership transfer permanently invalidates the previous owner's bearer, even if
-- ownership is later transferred back. Calendar deletion is handled by the FK.
CREATE OR REPLACE FUNCTION public.calendar_revoke_feed_on_owner_change() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN DELETE FROM public.calendar_external_feeds WHERE calendar_id=OLD.id; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS calendar_external_feed_owner_change ON public.calendars;
CREATE TRIGGER calendar_external_feed_owner_change BEFORE UPDATE OF owner_id ON public.calendars
FOR EACH ROW EXECUTE FUNCTION public.calendar_revoke_feed_on_owner_change();

-- Only the Edge service may resolve token hashes. No UUID calendar selector can
-- authorize this read, and anon/authenticated have no EXECUTE or direct table grants.
CREATE OR REPLACE FUNCTION public.calendar_feed_read(p_token_hash TEXT) RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE source public.calendars%ROWTYPE; events JSONB;
BEGIN
  IF p_token_hash IS NULL OR p_token_hash !~ '^[0-9a-f]{64}$' THEN RETURN NULL; END IF;
  SELECT c.* INTO source FROM public.calendar_external_feeds f JOIN public.calendars c ON c.id=f.calendar_id AND c.owner_id=f.owner_id
  WHERE f.token_hash=p_token_hash AND f.enabled;
  IF NOT FOUND THEN RETURN NULL; END IF;
  WITH native AS (
    SELECT jsonb_build_object('id',e.id,'title',e.title,'memo',e.memo,'all_day',e.all_day,'start_date',e.start_date,'end_date',e.end_date,
      'start_time',e.start_time,'end_time',e.end_time,'created_at',e.created_at,'updated_at',e.updated_at,
      'categories',coalesce((SELECT jsonb_agg(t.name ORDER BY ids.ordinal) FROM unnest(
        CASE WHEN cardinality(e.tag_ids)>0 THEN e.tag_ids WHEN e.tag_id IS NOT NULL THEN ARRAY[e.tag_id] ELSE '{}'::UUID[] END
      ) WITH ORDINALITY ids(id,ordinal) JOIN public.calendar_tags t ON t.id=ids.id),'[]'::JSONB)) value
    FROM public.calendar_events e WHERE e.calendar_id=source.id
  ), projected AS (
    SELECT jsonb_build_object('id',p->>'id','title',p->>'title','memo',p->>'memo','all_day',(p->>'all_day')::BOOLEAN,
      'start_date',p->>'start_date','end_date',p->>'end_date','start_time',p->>'start_time','end_time',p->>'end_time',
      'created_at',p->>'created_at','updated_at',p->>'updated_at','categories','[]'::JSONB) value
    FROM jsonb_array_elements(public.gantt_calendar_events(source.owner_id)) p
    WHERE p->>'calendar_id'=source.id::TEXT
  ), selected AS (SELECT value FROM native UNION ALL SELECT value FROM projected)
  SELECT coalesce(jsonb_agg(value ORDER BY value->>'start_date',value->>'id'),'[]'::JSONB) INTO events FROM selected;
  RETURN jsonb_build_object('calendar',jsonb_build_object('id',source.id,'name',source.name,'color',source.color),'events',events);
END $$;
REVOKE ALL ON FUNCTION public.calendar_session_feed_status(TEXT,UUID),public.calendar_session_feed_manage(TEXT,UUID,TEXT,TEXT,UUID),
  public.calendar_revoke_feed_on_owner_change(),public.calendar_feed_read(TEXT) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.calendar_session_feed_status(TEXT,UUID),public.calendar_session_feed_manage(TEXT,UUID,TEXT,TEXT,UUID) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.calendar_feed_read(TEXT) TO service_role;
NOTIFY pgrst,'reload schema';
COMMIT;
